url: https://peterwallin.github.io/
baseurl: /orderlypeople/

# Site settings
title: Orderly People
email: info@orderlypeople.se
description: "Orderly People - Professional medtech consultants Stockholm."


# Team names, titles and social links
people:
- name: Maria Jansson
  pic: 1
  position: VD
  social:
    - title: linkedin
      url: # https://www.linkedin.com/in/maria-jansson-3565635/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url:
  - title: facebook
    url:
  - title: linkedin
    url:
  - title: email
  url: info@orderlypeople.se

# Postal address (add as many lines as necessary)
address:
  - line: Folkungagatan 136
  - line: Stockholm Sverige

# Build settings
markdown: kramdown
permalink: pretty
